# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'smat_mode_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(QtWidgets.QWidget):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(423, 363)
        Dialog.setMinimumSize(QtCore.QSize(423, 363))
        Dialog.setMaximumSize(QtCore.QSize(423, 363))
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.checkBox = QtWidgets.QCheckBox(Dialog)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout.addWidget(self.checkBox)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.fontComboBox = QtWidgets.QFontComboBox(Dialog)
        self.fontComboBox.setObjectName("fontComboBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.fontComboBox)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.fontComboBox_2 = QtWidgets.QFontComboBox(Dialog)
        self.fontComboBox_2.setObjectName("fontComboBox_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.fontComboBox_2)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.fontComboBox_3 = QtWidgets.QFontComboBox(Dialog)
        self.fontComboBox_3.setObjectName("fontComboBox_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.fontComboBox_3)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 0, 2, 1, 1)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.gridLayout_2)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_4)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        #self.buttonBox.accepted.connect(Dialog.accept)
        #self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Smart Mode"))
        self.label.setWhatsThis(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Smart Mode allows you to download videos in one clieck.</span></p><p><span style=\" font-size:12pt;\">You just have to choose format, quality and output </span></p><p><span style=\" font-size:12pt;\">directory only one time and the application will apply your</span></p><p><span style=\" font-size:12pt;\">settings to all downloads.</span></p></body></html>"))
        self.label.setText(_translate("Dialog", "Smart Mode allows you to download videos in one click.\n"
"You just have to choose format, quality and output \n"
"directory only one time and the application will apply your\n"
"settings to all downloads."))
        self.checkBox.setText(_translate("Dialog", "Enable Smart Mode"))
        self.label_2.setText(_translate("Dialog", "Format"))
        self.label_3.setText(_translate("Dialog", "Quality"))
        self.label_5.setText(_translate("Dialog", "Subtitles"))
        self.label_6.setText(_translate("Dialog", "Directory"))
        self.pushButton.setText(_translate("Dialog", "Browse"))
        self.label_4.setText(_translate("Dialog", "Some videos may not be available in the selected\n"
"quality. In such cases, the videos wil be\n"
"downloaded in the closet quality to the one\n"
"you specified."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
